## @name Create-Poll
POST http://localhost:3333/polls
Content-Type: application/json

{
    "title":"Qual o melhor framework Node.JS",
    "options": ["Express","Fastify","NextJS","HapiJS"]
}


### @name Get-Poll
GET http://localhost:3333/polls/b4ac51c1-7a9b-4f4d-95b0-f57539b6d097

### @name Vote-On-Poll
POST http://localhost:3333/polls/b4ac51c1-7a9b-4f4d-95b0-f57539b6d097/votes
Content-Type: application/json

{
    "pollOptionId": "b0fe54a6-b8bf-441c-989e-c1960e0aa3fa"
}


# ### @name Web-socket
# WS ws://localhost:3333/polls/b4ac51c1-7a9b-4f4d-95b0-f57539b6d097/results
# Teste